apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 86.0.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/observability/prometheus/values.yaml
    - repoURL: git@github.com:nguyenductien-qnm/argocd-observability-lab.git
      targetRevision: main
      ref: values
