apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nguyenductien-qnm/argocd-observability-lab.git
    targetRevision: main
    path: rbac
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
