apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-developer
rules:
  - apiGroups: ["", "apps", "batch", "autoscaling", "argoproj.io"]
    resources:
      - "pods"
      - "pods/log"
      - "pods/exec"
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "services"
      - "configmaps"
      - "rollouts"
      - "jobs"
      - "cronjobs"
    verbs: ["*"]
