apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-binding-frontend
  namespace: frontend
subjects:
  - kind: Group
    name: "developer-group"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-developer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-binding-api
  namespace: api
subjects:
  - kind: Group
    name: "developer-group"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-developer
  apiGroup: rbac.authorization.k8s.io
