apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  smtp_password: b3ZuY3FlZ2xtb3J6d2dveg==
