apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: frontend
          image: 730335441285.dkr.ecr.ap-southeast-1.amazonaws.com/w9-image:sha-91c6d4a4de48680511dc6600aaf534695a5495fd
          ports:
            - containerPort: 80
