apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: api
          image: 730335441285.dkr.ecr.ap-southeast-1.amazonaws.com/w9-api-image:sha-93efcb0d0c6a86f1fe297333e7b00fa9f0c650fb
          ports:
            - containerPort: 3000
