name: Validate Manifests

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint all YAML files
        run: yamllint .

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.34.0

      - name: Validate Kubernetes manifests
        run: kubectl apply --dry-run=client --validate=false -f workloads/frontend/
